#!/usr/bin/env python
# -*- coding: utf-8 -*- #
from __future__ import unicode_literals
import os

##
AUTHOR = 'Liuchao'
SITENAME = 'Liung'
SITESUBTITLE = u'我如溪水，静静流淌在山涧~~我如白云，俯瞰此生今生~~'
SITEURL = 'http://liung.github.io'

# datetime config
# DEFAULT_DATE = (2014, 8, 26, 14, 0, 0)
DEFAULT_DATE = 'fs'    # use file system's mtime
DEFAULT_DATE_FORMAT = '%b %d, %Y'
TIMEZONE = 'Asia/Shanghai'
DEFAULT_LANG = 'zh_CN'

# 设置文章的URL（链接）
# 使用文件名作为文章或页面的slug（url）
FILENAME_METADATA = '(?P<slug>.*)'

# article config
ARTICLE_URL = 'blog/{category}/{slug}.html'
ARTICLE_SAVE_AS = ARTICLE_URL

# page config
PAGE_URL = 'pages/{slug}.html'
PAGE_SAVE_AS = PAGE_URL

# category config
DEFAULT_CATEGORY = u'其它'
CATEGORY_URL = 'category/{slug}/index.html'
CATEGORY_SAVE_AS = CATEGORY_URL
USE_FOLDER_AS_CATEGORY = True           # 使用目录名作为文章的分类名

# tag config
TAG_URL = 'tag/{slug}.html'
TAG_SAVE_AS = TAG_URL
TAGS_SAVE_AS = 'tag/index.html'

# author config
AUTHOR_URL = 'author/{slug}.html'
AUTHOR_SAVE_AS = AUTHOR_URL

# Feed generation is usually not desired when developing
FEED_ALL_ATOM = None
CATEGORY_FEED_ATOM = None
TRANSLATION_FEED_ATOM = None
AUTHOR_FEED_ATOM = None
AUTHOR_FEED_RSS = None
# RSS/Atom feeds
# FEED_DOMAIN = SITEURL
# FEED_ATOM = 'feeds/atom.xml'
# TAG_FEED_ATOM = 'feeds/tag.atom.xml'

# ----------------------------View-----------------------------
# set blog's theme
THEME = 'my-pelican-octopress-theme'
# Blog's menu
MENUITEMS = [(u'目  录', '/archives.html'),
             (u'主  页', SITEURL),
             ]
DISPLAY_PAGES_ON_MENU = True
DISPLAY_CATEGORIES_ON_MENU = False
SEARCH_BOX = True
NEWEST_FIRST_ARCHIVES = True
# pagination
DEFAULT_PAGINATION = 5
# summary
SUMMARY_MAX_LENGTH = 10
# set the properties of blog's sidebar images
SIDEBAR_IMAGE = 'images/author_photo.jpg'
SIDEBAR_IMAGE_WIDTH = 300
SIDEBAR_IMAGE_ALT = u'Liung'

# 设置Blog文件目录结构
PATH = 'content'
STATIC_PATHS = ['images', 'figures', 'downloads', 'favicon.jpg']
CODE_DIR = 'downloads/code'
NOTEBOOK_DIR = 'downloads/notebooks'

# plugin config
PLUGIN_PATHS = ['pelican-plugins/']
# PLUGINS = ['summary', 'liquid_tags.img', 'liquid_tags.video',
#            'liquid_tags.include_code',  # 'liquid_tags.notebook',
#            'liquid_tags.literal']

# The theme file should be updated so that the base header contains the line:
#
#  {% if EXTRA_HEADER %}
#    {{ EXTRA_HEADER }}
#  {% endif %}
#
# This header file is automatically generated by the notebook plugin
if not os.path.exists('_nb_header.html'):
    import warnings
    warnings.warn("_nb_header.html not found.  "
                  "Rerun make html to finalize build.")
else:
    # {theme_path}/templates/_includes/base.html use 'EXTRA_HEADER'
    EXTRA_HEADER = open('_nb_header.html').read()   # .decode('utf-8')

# Blogroll
LINKS = (('Pelican', 'http://getpelican.com/'),
         ('Python.org', 'http://python.org/'),
         ('Jinja2', 'http://jinja.pocoo.org/'),)

# Social widget
SOCIAL = ((u'新浪微博', 'http://www.weibo.com'),
          (u'Github', 'https://github.com/Liung'),)

# Uncomment following line if you want document-relative URLs when developing
RELATIVE_URLS = True

# sharing config
TWITTER_TWEET_BUTTON = True
TWITTER_USER = 'lc.pypi@gmail.com'
GOOGLE_PLUS_ONE = True
GOOGLE_PLUS_ID = 'lc.pypi@gmail.com'
FACEBOOK_LIKE = False

# comments util
DISQUS_SITENAME = "liunggithubio-aerodynamic"
GOOGLE_ANALYTICS = "UA-54228593-1"
